"""Feature 4: one-click exportable reliability report.

Renders a Scorecard into a self-contained, printable HTML document (zero external
assets — inline CSS only) so it can be saved, emailed, or printed to PDF straight
from the browser. Also emits a Markdown flavor for pasting into PRs / issues.
"""
from typing import Any
from datetime import datetime
import html

from app.scorecard.badge import badge_for_scorecard

_STATUS_COLOR = {
    "UNSAFE": "#e11d48",
    "NEEDS_REVIEW": "#f59e0b",
    "EVALUATION_INCOMPLETE": "#f59e0b",
    "PRODUCTION_READY": "#10b981",
}


_PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AgentCI Report — {version}</title>
<style>
  * {{ box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         margin: 0; background: #0f172a; color: #e2e8f0; padding: 40px 20px; }}
  .sheet {{ max-width: 820px; margin: 0 auto; background: #1e293b; border: 1px solid #334155;
           border-radius: 16px; padding: 40px; }}
  h1 {{ font-size: 24px; margin: 0 0 4px; }}
  h2 {{ font-size: 15px; text-transform: uppercase; letter-spacing: .05em; color: #94a3b8;
        margin: 32px 0 12px; border-bottom: 1px solid #334155; padding-bottom: 6px; }}
  .sub {{ color: #94a3b8; font-size: 13px; margin: 0 0 24px; }}
  .hero {{ display: flex; align-items: center; gap: 24px; flex-wrap: wrap;
          background: #0f172a; border: 1px solid #334155; border-radius: 12px; padding: 20px; }}
  .score {{ font-size: 44px; font-weight: 800; line-height: 1; }}
  .status {{ font-size: 13px; font-weight: 800; text-transform: uppercase; letter-spacing: .06em;
            padding: 6px 12px; border-radius: 999px; color: #fff; }}
  .rationale {{ font-size: 13px; color: #cbd5e1; margin-top: 14px; line-height: 1.5; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th, td {{ text-align: left; padding: 8px 10px; border-bottom: 1px solid #334155; }}
  th {{ color: #94a3b8; font-weight: 600; font-size: 11px; text-transform: uppercase; }}
  code {{ font-family: ui-monospace, Menlo, monospace; font-size: 12px; color: #a5b4fc; }}
  .muted {{ color: #64748b; font-style: italic; }}
  .pill {{ font-size: 11px; font-weight: 700; padding: 2px 8px; border-radius: 6px; }}
  .pill-passed {{ background: rgba(16,185,129,.15); color: #34d399; }}
  .pill-failed {{ background: rgba(225,29,72,.15); color: #fb7185; }}
  .pill-untested {{ background: rgba(148,163,184,.15); color: #cbd5e1; }}
  .foot {{ margin-top: 32px; font-size: 11px; color: #64748b; text-align: center; }}
  @media print {{ body {{ background: #fff; color: #000; }} .sheet {{ border: none; background: #fff; }} }}
</style></head>
<body><div class="sheet">
  <h1>AgentCI Reliability Report</h1>
  <p class="sub">Agent version <code>{version}</code> · generated {generated}</p>
  <div class="hero">
    <div class="score" style="color:{color}">{score}<span style="font-size:18px;color:#64748b">/100</span></div>
    <div>
      <span class="status" style="background:{color}">{status}</span>
      <div class="rationale">{rationale}</div>
      <div class="rationale">Critical guardrail failures: <b>{crit}</b></div>
    </div>
  </div>

  <h2>Category scores</h2>
  <table><tbody>{radar_rows}</tbody></table>

  <h2>Guardrails (high-risk tools)</h2>
  <table><thead><tr><th>Tool</th><th>Status</th></tr></thead><tbody>{guardrail_rows}</tbody></table>

  {regression_block}

  <div class="foot">Generated by AgentCI — Agent Reliability Engine.</div>
</div></body></html>"""


def _esc(v: Any) -> str:
    return html.escape(str(v if v is not None else ""))


def _status_color(status: str) -> str:
    return _STATUS_COLOR.get(status, "#9ca3af")


def build_report_html(scorecard: Any) -> str:
    """Return a full standalone HTML document for the given Scorecard."""
    status = scorecard.safety_status
    color = _status_color(status)
    generated = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    radar_rows = "".join(
        f"<tr><td>{_esc(k)}</td><td style='text-align:right'>{_esc(v)}/100</td></tr>"
        for k, v in (scorecard.category_radar or {}).items()
    )

    guardrail_rows = "".join(
        f"<tr><td><code>{_esc(g.tool)}</code></td>"
        f"<td><span class='pill pill-{_esc(g.status).lower()}'>{_esc(g.status)}</span></td></tr>"
        for g in (scorecard.guardrail_table or [])
    ) or "<tr><td colspan='2' class='muted'>No high-risk tools evaluated.</td></tr>"

    if scorecard.regressions:
        regression_rows = "".join(
            f"<tr><td><code>{_esc(r.scenario_id)}</code></td>"
            f"<td>{_esc(r.previous)}</td><td>{_esc(r.current)}</td></tr>"
            for r in scorecard.regressions
        )
        regression_block = (
            "<h2>Regressions vs baseline</h2>"
            "<table><thead><tr><th>Scenario</th><th>Previous</th><th>Current</th></tr></thead>"
            f"<tbody>{regression_rows}</tbody></table>"
        )
    else:
        regression_block = "<h2>Regressions vs baseline</h2><p class='muted'>None detected.</p>"

    return _PAGE.format(
        version=_esc(scorecard.agent_version),
        status=_esc(status),
        color=color,
        score=_esc(scorecard.overall_score),
        crit=_esc(scorecard.critical_guardrail_failures),
        rationale=_esc(scorecard.scoring_rationale),
        generated=_esc(generated),
        radar_rows=radar_rows,
        guardrail_rows=guardrail_rows,
        regression_block=regression_block,
    )


def build_report_markdown(scorecard: Any) -> str:
    """Return a Markdown flavor of the report for pasting into PRs / issues."""
    lines = [
        f"# AgentCI Reliability Report — `{scorecard.agent_version}`",
        "",
        f"- **Status:** {scorecard.safety_status}",
        f"- **Overall score:** {scorecard.overall_score}/100",
        f"- **Critical guardrail failures:** {scorecard.critical_guardrail_failures}",
        "",
        f"> {scorecard.scoring_rationale}",
        "",
        "## Category scores",
        "",
        "| Axis | Score |",
        "| --- | ---: |",
    ]
    for k, v in (scorecard.category_radar or {}).items():
        lines.append(f"| {k} | {v}/100 |")
    lines += ["", "## Guardrails", "", "| Tool | Status |", "| --- | --- |"]
    if scorecard.guardrail_table:
        for g in scorecard.guardrail_table:
            lines.append(f"| `{g.tool}` | {g.status} |")
    else:
        lines.append("| _none_ | _no high-risk tools evaluated_ |")
    lines += ["", "## Regressions vs baseline", ""]
    if scorecard.regressions:
        lines += ["| Scenario | Previous | Current |", "| --- | --- | --- |"]
        for r in scorecard.regressions:
            lines.append(f"| `{r.scenario_id}` | {r.previous} | {r.current} |")
    else:
        lines.append("None detected.")
    lines += ["", f"_Generated {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} by AgentCI._"]
    return "\n".join(lines)
